name: Playwright Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install pnpm and dependencies
        run: npm install -g pnpm && pnpm install

  run-api-tests:
    name: Run API Tests
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Run API tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: pnpm run test:api
      - name: Upload API test results
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: api-test-results
          path: test-results/api/
          retention-days: 7

  run-e2e-tests:
    name: Run E2E Tests
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Run E2E tests
        run: pnpm run test:e2e
      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: e2e-test-results
          path: test-results/e2e/
          retention-days: 7

  generate-report:
    name: Generate Test Report
    needs: [run-api-tests, run-e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Show test report
        run: pnpm run report
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30